# Generated by Django 5.2.8 on 2025-11-11 06:10

import json
from django.db import migrations, models


def copy_content_to_text(apps, schema_editor):
    Data = apps.get_model('data', 'Data')
    for obj in Data.objects.all():
        content = getattr(obj, 'content', None)
        text_value = ''
        if isinstance(content, str):
            text_value = content
        elif isinstance(content, dict):
            if isinstance(content.get('text'), str):
                text_value = content['text']
            else:
                first_string = next((v for v in content.values() if isinstance(v, str)), None)
                if first_string is not None:
                    text_value = first_string
                else:
                    text_value = json.dumps(content, ensure_ascii=False)
        elif content is not None:
            text_value = str(content)
        obj.text = text_value
        obj.save(update_fields=['text'])


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_data_options_data_created_at_data_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='text',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.RunPython(copy_content_to_text, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='data',
            name='content',
        ),
    ]
