# Generated by Django 5.2.8 on 2025-11-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_data_content_data_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.CharField(max_length=1024),
        ),
    ]
